# Generated by Django 3.1.6 on 2021-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
