# Generated by Django 3.1.6 on 2021-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionpost', '0003_auto_20210223_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('甘口', '甘口'), ('辛口', '辛口'), ('旨口', '旨口')], max_length=50),
        ),
    ]
